### ISSUE TITLE
Incorrect behavior when aborting download in v0.8

### ISSUE THREAD

**Issue by sohaib17** [lexiforest/curl-impersonate#82]
### Problem

libcurl provides a `WRITEFUNCTION` [option](https://curl.se/libcurl/c/CURLOPT_WRITEFUNCTION.html) to process response chunks. Its behavior is to abort the download if returned integer is not equal to the length of passed chunk.

> Your callback should return the number of bytes actually taken care of. If that amount differs from the amount passed to your callback function, it signals an error condition to the library. This causes the transfer to get aborted and the libcurl function used returns [CURLE_WRITE_ERROR](https://curl.se/libcurl/c/libcurl-errors.html#CURLEWRITEERROR).

It looks like instead of `E_WRITE_ERROR`, latest `libcurl-impersonate` is returning `E_RECV_ERROR` which breaks the abort functionality and makes it impossible to differentiate between server side receive errors/timeouts and on-purpose aborts.

### Test Case

Following is the minimal test case with `pycurl` that can be used to reproduce this:
```
import pycurl

print(pycurl.version)

url = 'https://bit.ly/4874LxR'


def abort_write(_):
    '''
    Abort writing response body.
    '''
    return -1


curl = pycurl.Curl()
curl.setopt(pycurl.URL, url.encode('utf-8'))
curl.setopt(pycurl.FOLLOWLOCATION, 1)
curl.setopt(pycurl.WRITEFUNCTION, abort_write)
curl.perform()
curl.close()

```

### Results

Use `LD_PRELOAD` to load `libcurl-impersonate 0.8.0` and run the test. Error `56 (E_RECV_ERROR)` will return:

```
$ LD_PRELOAD=/local/lib/libcurl-0.8.0.so CURL_IMPERSONATE=chrome124 python pycurl_test.py 

PycURL/7.45.3 libcurl/8.7.0-DEV BoringSSL zlib/1.3 brotli/1.1.0 zstd/1.5.6 nghttp2/1.63.0

Traceback (most recent call last):
  File "/home/ubuntu/pycurl_test.py", line 22, in <module>
    curl.perform()

pycurl.error: (56, 'Failure writing output to destination, passed 1369 returned -1')
```

I tried the same test case with `libcurl-impersonate 0.7.0b1` built with older `libcurl v8.5` and it passed:
```
$ LD_PRELOAD=/local/lib/libcurl-0.7.0b1.so CURL_IMPERSONATE=chrome124 python pycurl_test.py 

PycURL/7.45.3 libcurl/8.5.0 BoringSSL zlib/1.3 brotli/1.0.9 zstd/1.5.6 nghttp2/1.56.0

Traceback (most recent call last):
  File "/home/ubuntu/pycurl_test.py", line 22, in <module>
    curl.perform()

pycurl.error: (23, 'Failure writing output to destination')
```

Error `23 (E_WRITE_ERROR)` is the expected code, which allows client to handle on-purpose aborts and process the result. Something got broken in latest impersonation patch or maybe in libcurl v8.7.1 itself. Strangely though, version API returns 8.7.1 as `8.7.0-DEV` implying that it is not stable.

**Comment by lexiforest** [comment]
Thanks for the detailed report. I'll verify the behavior later. 

As for the version API, I noticed it a while ago. I did use the v8.7.1 tag from curl repository, you can take a look at the Makefiles, however, the compiled binary does not show this version. There might be something wrong with the build arguments or something like that.

**Comment by lexiforest** [comment]
I have verified that this is no longer an issue in 1.0.0rc2.

```
╰─>$ DYLD_INSERT_LIBRARIES=/usr/local/lib/libcurl-impersonate.4.dylib python issues/pc.py                                                      
PycURL/7.45.2 libcurl/8.13.0-IMPERSONATE BoringSSL zlib/1.2.12 brotli/1.1.0 zstd/1.5.7 libidn2/2.3.8 nghttp2/1.63.0 ngtcp2/1.11.0 nghttp3/1.9.0
Traceback (most recent call last):                                                                                                             
  File "/Users/yifei/repos/curl_cffi/issues/pc.py", line 19, in <module>                                                                       
    curl.perform()                                                                                                                             
pycurl.error: (23, 'Failure writing output to destination, passed 1073 returned -1')                                                           
```

As for the `-DEV` postfix, it seems that this should be replaced by package maintainers, so I changed it to `-IMPERSONATE`.
